name: Bebebai Sky Sentinel Cron
on:
  schedule:
    - cron: '20,50 * * * *' 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Di-upgrade ke v4 biar anti-warning
      - name: Set up Python
        uses: actions/setup-python@v5 # Di-upgrade ke v5 biar stabil
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: pip install requests supabase
      - name: Run Sentinel System
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          OPENWEATHER_API_KEY: ${{ secrets.OPENWEATHER_API_KEY }}
          TELEGRAM_CHAT_IDS: ${{ secrets.TELEGRAM_CHAT_IDS }}
        run: python github_guardian.py